timezone: "Europe/Moscow"

channels:
  first_squad:
    team_guild_id: "1255670937928339557"
    team_role_id: "1255696114565251173"
    tagging_emoji_id: "1451139283955224576"
    tagging_emoji_name: "Confederate_Flag"
    pick_day: saturday
    schedules:
      - poll: friday_event
        channel_id: "1356267150112981212"
        title: "Пятничный ивент ({date}) UEC в 22:00 по МСК!"
        day: friday
        at: "22:00"
      - poll: training
        channel_id: "1356267150112981212"
        title: "Полковая тренировка перед Ивентом ({date}) в 21:00 по МСК!"
        day: saturday
        at: "21:00"
      - poll: saturday_event
        channel_id: "1356267150112981212"
        title: "Субботний ивент ({date}) UEC в 22:00 по МСК!"
        day: saturday
        at: "22:00"
      - poll: picket_patrole
        channel_id: "1356267150112981212"
        title: "Полковой Пикет-Патруль ({date}) UEC в 20:00 по МСК!"
        day: sunday
        at: "20:00"
    polls:
      - name: friday_event
        label: "Пятничный ивент"
        duration_hours: 72
        allow_multiselect: false
        answers:
          - text: "Иду"
            emoji_name: "nekocatgun"
            emoji_id: "1452231780164702283"
          - text: "Опоздаю"
            emoji_name: "catlyingonfloor"
            emoji_id: "1452231567228407840"
          - text: "Не иду"
            emoji_name: "cattoshyblush"
            emoji_id: "1452231655942258712"
      - name: saturday_event
        label: "Субботний ивент"
        duration_hours: 72
        allow_multiselect: false
        answers:
          - text: "Иду"
            emoji_name: "nekocatgun"
            emoji_id: "1452231780164702283"
          - text: "Опоздаю"
            emoji_name: "catlyingonfloor"
            emoji_id: "1452231567228407840"
          - text: "Не иду"
            emoji_name: "cattoshyblush"
            emoji_id: "1452231655942258712"
      - name: training
        label: "Полковая тренировка"
        duration_hours: 72
        allow_multiselect: false
        answers:
          - text: "Иду"
            emoji_name: "BOBROFANTERIA"
            emoji_id: "1451138942135959574"
          - text: "Опоздаю"
            emoji_name: "catlyingonfloor"
            emoji_id: "1452231567228407840"
          - text: "Не иду"
            emoji_name: "cattoshyblush"
            emoji_id: "1452231655942258712"
      - name: picket_patrole
        label: "Пикет патруль"
        duration_hours: 72
        allow_multiselect: false
        answers:
          - text: "Иду"
            emoji_name: "BOBROFANTERIA"
            emoji_id: "1451138942135959574"
          - text: "Опоздаю"
            emoji_name: "catlyingonfloor"
            emoji_id: "1452231567228407840"
          - text: "Не иду"
            emoji_name: "cattoshyblush"
            emoji_id: "1452231655942258712"
  second_squad:
    team_guild_id: "1391892744934527006"
    team_role_id: "1391896118333276242"
    tagging_emoji_id: "1436992023470149634"
    tagging_emoji_name: "Infantry_enlisted"
    pick_day: wednesday
    schedules:
      - poll: friday_event
        channel_id: "1391892746855383124"
        title: "Пятничный ивент ({date}) UEC в 22:00 по МСК!"
        day: friday
        at: "22:00"
      - poll: training
        channel_id: "1391892746855383124"
        title: "Полковая тренировка перед Ивентом ({date}) в 21:00 по МСК!"
        day: saturday
        at: "21:00"
      - poll: saturday_event
        channel_id: "1391892746855383124"
        title: "Субботний ивент ({date}) UEC в 22:00 по МСК!"
        day: saturday
        at: "22:00"
      - poll: picket_patrole
        channel_id: "1391892746855383124"
        title: "Полковой Пикет-Патруль ({date}) UEC в 20:00 по МСК!"
        day: sunday
        at: "20:00"
    polls:
      - name: friday_event
        label: "Пятничный ивент"
        duration_hours: 72
        allow_multiselect: false
        answers:
          - text: "Иду"
            emoji_name: "Mobile_Cadets"
            emoji_id: "1430158546590240768"
          - text: "Опоздаю"
            emoji_name: "Wojak_sorrows"
            emoji_id: "1430805290818998304"
          - text: "Не иду"
            emoji_name: "Stidno"
            emoji_id: "1431203945346498671"
      - name: saturday_event
        label: "Субботний ивент"
        duration_hours: 72
        allow_multiselect: false
        answers:
          - text: "Иду"
            emoji_name: "Tony"
            emoji_id: "1501593704861929663"
          - text: "Опоздаю"
            emoji_name: "Wojak_seen"
            emoji_id: "1430805246367760384"
          - text: "Не иду"
            emoji_name: "Stidno"
            emoji_id: "1431203945346498671"
      - name: training
        label: "Полковая тренировка"
        duration_hours: 72
        allow_multiselect: false
        answers:
          - text: "Иду"
            emoji_name: "Mobile_Cadets"
            emoji_id: "1430158546590240768"
          - text: "Опоздаю"
            emoji_name: "Derzhi_Dorogoy"
            emoji_id: "1443507354116161646"
          - text: "Не иду"
            emoji_name: "Stidno"
            emoji_id: "1431203945346498671"
      - name: picket_patrole
        label: "Пикет патруль"
        duration_hours: 72
        allow_multiselect: false
        answers:
          - text: "Иду"
            emoji_name: "Mobile_Cadets"
            emoji_id: "1430158546590240768"
          - text: "Опоздаю"
            emoji_name: "Wojak_sorrows"
            emoji_id: "1430805290818998304"
          - text: "Не иду"
            emoji_name: "Stidno"
            emoji_id: "1431203945346498671"

  third_squad:
    team_guild_id: "1442154882260795435"
    team_role_id: "1442160755834224691"
    tagging_emoji_id: "1442258138920124466"
    tagging_emoji_name: "Infantry_Badge"
    pick_day: thursday
    schedules:
      - poll: friday_event
        channel_id: "1442154882646933563"
        title: "Пятничный ивент ({date}) UEC в 22:00 по МСК!"
        day: friday
        at: "22:00"
      - poll: training
        channel_id: "1442154882646933563"
        title: "Полковая тренировка перед Ивентом ({date}) в 21:00 по МСК!"
        day: saturday
        at: "21:00"
      - poll: saturday_event
        channel_id: "1442154882646933563"
        title: "Субботний ивент ({date}) UEC в 22:00 по МСК!"
        day: saturday
        at: "22:00"
      - poll: picket_patrole
        channel_id: "1442154882646933563"
        title: "Полковой Пикет-Патруль ({date}) UEC в 20:00 по МСК!"
        day: sunday
        at: "20:00"
    polls:
      - name: friday_event
        label: "Пятничный ивент"
        duration_hours: 72
        allow_multiselect: false
        answers:
          - text: "Иду"
            emoji_name: "LA_TIGERZOUAVEBALL"
            emoji_id: "1491383720735805480"
          - text: "Опоздаю"
            emoji_name: "Stydno"
            emoji_id: "1491366262121435176"
          - text: "Не иду"
            emoji_name: "Busya"
            emoji_id: "1442280732948037642"
      - name: saturday_event
        label: "Субботний ивент"
        duration_hours: 72
        allow_multiselect: false
        answers:
          - text: "Иду"
            emoji_name: "LA_TIGERZOUAVEBALL"
            emoji_id: "1491383720735805480"
          - text: "Опоздаю"
            emoji_name: "Stydno"
            emoji_id: "1491366262121435176"
          - text: "Не иду"
            emoji_name: "Busya"
            emoji_id: "1442280732948037642"
      - name: training
        label: "Полковая тренировка"
        duration_hours: 72
        allow_multiselect: false
        answers:
          - text: "Иду"
            emoji_name: "CHAAAAAAAAAARRRGE"
            emoji_id: "1442847287075278991"
          - text: "Опоздаю"
            emoji_name: "Salli_Nasvaenko"
            emoji_id: "1495856747590586462"
          - text: "Не иду"
            emoji_name: "Popali"
            emoji_id: "1491364365390057573"
      - name: picket_patrole
        label: "Пикет патруль"
        duration_hours: 72
        allow_multiselect: false
        answers:
          - text: "Иду"
            emoji_name: "CHAAAAAAAAAARRRGE"
            emoji_id: "1442847287075278991"
          - text: "Опоздаю"
            emoji_name: "Salli_Nasvaenko"
            emoji_id: "1495856747590586462"
          - text: "Не иду"
            emoji_name: "Popali"
            emoji_id: "1491364365390057573"
